export const iotProjects = [
  {
    id: "earlynx",
    title: "Earlynx",
    subtitle: "AI Cancer Screening",
    badge: "🏆 Champion 2026",
    badgeBlue: true,
    tags: ["Embedded AI", "Sensor Fusion", "CNN Model"],
    desc: "Non-invasive diagnostic prototype using sensor fusion to analyze saliva samples for early cancer detection. Evaluated by DOST.",
    statusLabel: "Life & Science Category",
    statusColor: "#30d158",
    accentRgb: "48, 209, 88",
    image: "/images/earlynx.png",
  },
  {
    id: "air-filtration",
    title: "Air Filtration",
    subtitle: "Piggery IoT System",
    badge: "🏆 Champion 2026",
    badgeBlue: true,
    tags: ["Arduino Uno", "MQ137 Sensor", "DOST Verified"],
    desc: "Smart air quality filtration device for piggery environments. Congress Innovation Category champion.",
    statusLabel: "Innovation Category",
    statusColor: "#30d158",
    accentRgb: "48, 209, 88",
    image: "/images/airfilter.png",
  },
  {
    id: "gridsonar",
    title: "GridSonar",
    subtitle: "Power Grid Management",
    badge: "Patent Pending",
    badgeBlue: false,
    tags: ["Mesh Architecture", "Predictive AI", "Fault Detection"],
    desc: "Self-healing mesh submetering system with real-time fault detection and predictive AI for power grid management.",
    statusLabel: "In Market",
    statusColor: "#2997ff",
    accentRgb: "41, 151, 255",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80",
  },
];

export const platformProjects = [
  {
    id: "axonis",
    title: "AXONIS Platform",
    subtitle: "AI Safety OS",
    tag: "Active Dev",
    tagColor: "#2997ff",
    dot: "#2997ff",
    accentRgb: "41, 151, 255",
    desc: "Open-core AI safety OS for critical infrastructure. Decentralized, built for the real world.",
    cta: "Learn more",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
  },
  {
    id: "minesafe",
    title: "MineSafe AI",
    subtitle: "Mining Hazard Detection",
    tag: "Stage 0",
    tagColor: "rgba(255,255,255,0.45)",
    dot: "rgba(255,255,255,0.30)",
    accentRgb: "255,255,255",
    desc: "Mining hazard detection engine using computer vision and environmental sensors.",
    cta: "Learn more",
    image: "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&q=80",
  },
  {
    id: "school",
    title: "School Systems",
    subtitle: "Education Management",
    tag: "Live",
    tagColor: "#30d158",
    dot: "#30d158",
    accentRgb: "48, 209, 88",
    desc: "Enrollment, grading, and management systems deployed in educational institutions.",
    cta: "Learn more",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80",
  },
  {
    id: "dashboards",
    title: "Business Dashboards",
    subtitle: "Analytics & Operations",
    tag: "Deployed",
    tagColor: "#30d158",
    dot: "#30d158",
    accentRgb: "48, 209, 88",
    desc: "Custom analytics and operations dashboards for businesses.",
    cta: "Learn more",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
  },
];
